In [6]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

In [7]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15945405,Lewis,567,France,Male,58,0,13674.54,1,1,1,144022.31,0
1,2,15951000,Williams,571,Germany,Male,43,8,0.00,2,1,1,65399.77,0
2,3,15630085,Jones,628,Spain,Female,30,1,0.00,3,1,1,63760.04,0
3,4,15830429,Thomas,685,Spain,Female,44,8,107540.45,1,0,0,55274.68,1
4,5,15615278,King,737,France,Female,18,9,204248.69,2,0,0,176273.19,0

In [8]:
## Preprocess the Data

data = data.drop(['RowNumber','CustomerId','Surname'],axis = 1)

In [9]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,567,France,Male,58,0,13674.54,1,1,1,144022.31,0
1,571,Germany,Male,43,8,0.00,2,1,1,65399.77,0
2,628,Spain,Female,30,1,0.00,3,1,1,63760.04,0
3,685,Spain,Female,44,8,107540.45,1,0,0,55274.68,1
4,737,France,Female,18,9,204248.69,2,0,0,176273.19,0
...,...,...,...,...,...,...,...,...,...,...,...
995,596,France,Female,54,8,215021.93,2,1,1,168623.76,0
996,747,Germany,Female,28,3,0.00,1,1,1,65839.12,0
997,848,France,Male,39,8,0.00,1,1,1,20811.28,0
998,499,Germany,Male,34,1,35779.44,2,1,1,19973.51,1
999,471,France,Male,23,9,34279.31,3,0,0,91210.33,0

In [10]:
## label encoder
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [11]:
## One Hot Enocde 'GeoGraphy'ArithmeticError
ohe_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=ohe_geo.get_feature_names_out(['Geography']))

In [12]:
geo_encoded_df

     Geography_France  Geography_Germany  Geography_Spain
0                 1.0                0.0              0.0
1                 0.0                1.0              0.0
2                 0.0                0.0              1.0
3                 0.0                0.0              1.0
4                 1.0                0.0              0.0
..                ...                ...              ...
995               1.0                0.0              0.0
996               0.0                1.0              0.0
997               1.0                0.0              0.0
998               0.0                1.0              0.0
999               1.0                0.0              0.0

[1000 rows x 3 columns]

In [14]:
## Combine ohe-hot encoded column with original data
from matplotlib import axis


data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,567,1,58,0,13674.54,1,1,1,144022.31,0,1.0,0.0,0.0
1,571,1,43,8,0.00,2,1,1,65399.77,0,0.0,1.0,0.0
2,628,0,30,1,0.00,3,1,1,63760.04,0,0.0,0.0,1.0
3,685,0,44,8,107540.45,1,0,0,55274.68,1,0.0,0.0,1.0
4,737,0,18,9,204248.69,2,0,0,176273.19,0,1.0,0.0,0.0