In [39]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

In [40]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15945405,Lewis,567,France,Male,58,0,13674.54,1,1,1,144022.31,0
1,2,15951000,Williams,571,Germany,Male,43,8,0.00,2,1,1,65399.77,0
2,3,15630085,Jones,628,Spain,Female,30,1,0.00,3,1,1,63760.04,0
3,4,15830429,Thomas,685,Spain,Female,44,8,107540.45,1,0,0,55274.68,1
4,5,15615278,King,737,France,Female,18,9,204248.69,2,0,0,176273.19,0

In [41]:
## Preprocess the Data

data = data.drop(['RowNumber','CustomerId','Surname'],axis = 1)

In [42]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,567,France,Male,58,0,13674.54,1,1,1,144022.31,0
1,571,Germany,Male,43,8,0.00,2,1,1,65399.77,0
2,628,Spain,Female,30,1,0.00,3,1,1,63760.04,0
3,685,Spain,Female,44,8,107540.45,1,0,0,55274.68,1
4,737,France,Female,18,9,204248.69,2,0,0,176273.19,0
...,...,...,...,...,...,...,...,...,...,...,...
995,596,France,Female,54,8,215021.93,2,1,1,168623.76,0
996,747,Germany,Female,28,3,0.00,1,1,1,65839.12,0
997,848,France,Male,39,8,0.00,1,1,1,20811.28,0
998,499,Germany,Male,34,1,35779.44,2,1,1,19973.51,1
999,471,France,Male,23,9,34279.31,3,0,0,91210.33,0

In [43]:
## label encoder
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [44]:
## One Hot Enocde 'GeoGraphy'ArithmeticError
ohe_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=ohe_geo.get_feature_names_out(['Geography']))

In [45]:
geo_encoded_df

     Geography_France  Geography_Germany  Geography_Spain
0                 1.0                0.0              0.0
1                 0.0                1.0              0.0
2                 0.0                0.0              1.0
3                 0.0                0.0              1.0
4                 1.0                0.0              0.0
..                ...                ...              ...
995               1.0                0.0              0.0
996               0.0                1.0              0.0
997               1.0                0.0              0.0
998               0.0                1.0              0.0
999               1.0                0.0              0.0

[1000 rows x 3 columns]

In [46]:
## Combine ohe-hot encoded column with original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,567,1,58,0,13674.54,1,1,1,144022.31,0,1.0,0.0,0.0
1,571,1,43,8,0.00,2,1,1,65399.77,0,0.0,1.0,0.0
2,628,0,30,1,0.00,3,1,1,63760.04,0,0.0,0.0,1.0
3,685,0,44,8,107540.45,1,0,0,55274.68,1,0.0,0.0,1.0
4,737,0,18,9,204248.69,2,0,0,176273.19,0,1.0,0.0,0.0

In [47]:
## Split the data into features and target

X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [48]:
## Split the data in training and testing sets

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [49]:
scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [52]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('ohe_geo.pkl','wb') as file:
    pickle.dump(ohe_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statement

In [53]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [54]:
## Build the Model
from sklearn import metrics


model = Sequential([
    Dense(64, activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) ## Output Layer for Regression
])

## Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

f:\PYTHON_AI\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
import tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

## Set up TensorBoard
log_dir = "regressionlogs/fit/" +datetime.datetime.now().strftime("%Y%m/%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [62]:
## Setup EarlyStopping
early_stopping_calback =EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [63]:
history = model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_calback,tensorboard_callback]
    )

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 49458.0234 - mae: 49458.0234 - val_loss: 54381.5742 - val_mae: 54381.5742
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 49299.7812 - mae: 49299.7812 - val_loss: 54133.9609 - val_mae: 54133.9609
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 49137.8086 - mae: 49137.8086 - val_loss: 53912.8867 - val_mae: 53912.8867
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 48998.5508 - mae: 48998.5508 - val_loss: 53699.1367 - val_mae: 53699.1367
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 48859.8789 - mae: 48859.8789 - val_loss: 53501.8633 - val_mae: 53501.8633
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 48729.5000 - mae: 48729.5000 - val_loss: 53284.2852 - val_mae: 53284.2852
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 48601.7969 - mae: 48601.7969 - val_loss: 53107.0156 - val_mae: 53107.0156
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 48484.2812 - mae: 48484.2812 - val_loss: 52936.6250 - val_mae: 52936.6250
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 48384.8711 - mae: 48384.8711 - val_loss: 52781.2969 - val_mae: 52781.2969
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 48296.4688 - mae: 48296.4688 - val_loss: 52664.7969 - val_mae: 52664.7969
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 48215.8047 - mae: 48215.8047 - val_loss: 52537.7500 - val_mae: 52537.7500
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 48138.5664 - mae: 48138.5664 - val_loss: 52409.8984 - val_mae: 52409.8984
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 48063.6016 - mae: 48063.6016 - val_loss: 52268.2305 - val_mae: 52268.2305
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47992.9453 - mae: 47992.9453 - val_loss: 52172.1914 - val_mae: 52172.1914
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 47924.0586 - mae: 47924.0586 - val_loss: 52036.7969 - val_mae: 52036.7969
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47865.8242 - mae: 47865.8242 - val_loss: 51929.2891 - val_mae: 51929.2891
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 47815.3438 - mae: 47815.3438 - val_loss: 51839.0156 - val_mae: 51839.0156
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 47768.7695 - mae: 47768.7695 - val_loss: 51739.6445 - val_mae: 51739.6445
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47722.0352 - mae: 47722.0352 - val_loss: 51658.3906 - val_mae: 51658.3906
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47685.6367 - mae: 47685.6367 - val_loss: 51609.0391 - val_mae: 51609.0391
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 47642.9531 - mae: 47642.9531 - val_loss: 51526.2148 - val_mae: 51526.2148
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47606.0039 - mae: 47606.0039 - val_loss: 51467.5508 - val_mae: 51467.5508
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47575.4297 - mae: 47575.4297 - val_loss: 51408.0781 - val_mae: 51408.0781
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47532.8711 - mae: 47532.8711 - val_loss: 51364.2344 - val_mae: 51364.2344
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47497.0547 - mae: 47497.0547 - val_loss: 51315.7031 - val_mae: 51315.7031
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 47468.4609 - mae: 47468.4609 - val_loss: 51253.1406 - val_mae: 51253.1406
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 47434.0703 - mae: 47434.0703 - val_loss: 51227.2617 - val_mae: 51227.2617
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 47410.6016 - mae: 47410.6016 - val_loss: 51178.1797 - val_mae: 51178.1797
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 47385.5000 - mae: 47385.5000 - val_loss: 51138.7969 - val_mae: 51138.7969
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47359.4805 - mae: 47359.4805 - val_loss: 51096.1055 - val_mae: 51096.1055
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 47335.1250 - mae: 47335.1250 - val_loss: 51062.0195 - val_mae: 51062.0195
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47317.6719 - mae: 47317.6719 - val_loss: 51040.0352 - val_mae: 51040.0352
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47296.2656 - mae: 47296.2656 - val_loss: 50982.7656 - val_mae: 50982.7656
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 47275.6719 - mae: 47275.6719 - val_loss: 50978.9766 - val_mae: 50978.9766
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 47249.8438 - mae: 47249.8438 - val_loss: 50919.8047 - val_mae: 50919.8047
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 47229.3594 - mae: 47229.3594 - val_loss: 50889.9453 - val_mae: 50889.9453
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 47207.3594 - mae: 47207.3594 - val_loss: 50853.1758 - val_mae: 50853.1758
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 47189.1758 - mae: 47189.1758 - val_loss: 50819.5508 - val_mae: 50819.5508
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 47175.6602 - mae: 47175.6602 - val_loss: 50792.9062 - val_mae: 50792.9062
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47154.4688 - mae: 47154.4688 - val_loss: 50759.3984 - val_mae: 50759.3984
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47132.6094 - mae: 47132.6094 - val_loss: 50745.6562 - val_mae: 50745.6562
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47116.9414 - mae: 47116.9414 - val_loss: 50724.3398 - val_mae: 50724.3398
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 47100.1641 - mae: 47100.1641 - val_loss: 50687.7344 - val_mae: 50687.7344
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47082.8750 - mae: 47082.8750 - val_loss: 50664.5938 - val_mae: 50664.5938
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 47068.1797 - mae: 47068.1797 - val_loss: 50635.2852 - val_mae: 50635.2852
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47054.8086 - mae: 47054.8086 - val_loss: 50630.9531 - val_mae: 50630.9531
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47035.8711 - mae: 47035.8711 - val_loss: 50626.3242 - val_mae: 50626.3242
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47030.8438 - mae: 47030.8438 - val_loss: 50590.3516 - val_mae: 50590.3516
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 47014.2266 - mae: 47014.2266 - val_loss: 50592.3789 - val_mae: 50592.3789
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 47001.7695 - mae: 47001.7695 - val_loss: 50569.5000 - val_mae: 50569.5000
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46985.3086 - mae: 46985.3086 - val_loss: 50559.3398 - val_mae: 50559.3398
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46972.3945 - mae: 46972.3945 - val_loss: 50534.8711 - val_mae: 50534.8711
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 46965.0312 - mae: 46965.0312 - val_loss: 50506.8047 - val_mae: 50506.8047
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46948.5391 - mae: 46948.5391 - val_loss: 50504.5156 - val_mae: 50504.5156
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46937.2109 - mae: 46937.2109 - val_loss: 50499.8438 - val_mae: 50499.8438
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46925.2656 - mae: 46925.2656 - val_loss: 50471.1055 - val_mae: 50471.1055
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 46918.0117 - mae: 46918.0117 - val_loss: 50468.8047 - val_mae: 50468.8047
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46908.2344 - mae: 46908.2344 - val_loss: 50462.8867 - val_mae: 50462.8867
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46896.9688 - mae: 46896.9688 - val_loss: 50448.1719 - val_mae: 50448.1719
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46887.8750 - mae: 46887.8750 - val_loss: 50426.2500 - val_mae: 50426.2500
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46878.5195 - mae: 46878.5195 - val_loss: 50432.6250 - val_mae: 50432.6250
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46865.6094 - mae: 46865.6094 - val_loss: 50417.9297 - val_mae: 50417.9297
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46856.9961 - mae: 46856.9961 - val_loss: 50416.7891 - val_mae: 50416.7891
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 46851.1250 - mae: 46851.1250 - val_loss: 50419.6758 - val_mae: 50419.6758
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46834.6289 - mae: 46834.6289 - val_loss: 50395.5039 - val_mae: 50395.5039
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46826.1289 - mae: 46826.1289 - val_loss: 50378.5898 - val_mae: 50378.5898
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46818.0039 - mae: 46818.0039 - val_loss: 50375.8398 - val_mae: 50375.8398
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46808.7461 - mae: 46808.7461 - val_loss: 50363.3789 - val_mae: 50363.3789
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46801.3398 - mae: 46801.3398 - val_loss: 50348.1602 - val_mae: 50348.1602
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 46787.2383 - mae: 46787.2383 - val_loss: 50349.2734 - val_mae: 50349.2734
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46782.7305 - mae: 46782.7305 - val_loss: 50347.7891 - val_mae: 50347.7891
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46773.4883 - mae: 46773.4883 - val_loss: 50326.1367 - val_mae: 50326.1367
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46765.0742 - mae: 46765.0742 - val_loss: 50309.6758 - val_mae: 50309.6758
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 46751.5742 - mae: 46751.5742 - val_loss: 50307.8906 - val_mae: 50307.8906
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46747.3047 - mae: 46747.3047 - val_loss: 50318.9336 - val_mae: 50318.9336
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46741.0508 - mae: 46741.0508 - val_loss: 50289.1953 - val_mae: 50289.1953
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46735.0195 - mae: 46735.0195 - val_loss: 50291.6953 - val_mae: 50291.6953
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46723.5469 - mae: 46723.5469 - val_loss: 50270.5703 - val_mae: 50270.5703
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46715.8789 - mae: 46715.8789 - val_loss: 50275.4492 - val_mae: 50275.4492
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46711.5195 - mae: 46711.5195 - val_loss: 50257.8516 - val_mae: 50257.8516
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46703.5156 - mae: 46703.5156 - val_loss: 50261.9062 - val_mae: 50261.9062
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46695.8281 - mae: 46695.8281 - val_loss: 50250.6445 - val_mae: 50250.6445
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 46691.1094 - mae: 46691.1094 - val_loss: 50243.1445 - val_mae: 50243.1445
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46683.6562 - mae: 46683.6562 - val_loss: 50258.7188 - val_mae: 50258.7188
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46680.5547 - mae: 46680.5547 - val_loss: 50248.0469 - val_mae: 50248.0469
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46670.4766 - mae: 46670.4766 - val_loss: 50236.8242 - val_mae: 50236.8242
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46668.6797 - mae: 46668.6797 - val_loss: 50232.1562 - val_mae: 50232.1562
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46661.7617 - mae: 46661.7617 - val_loss: 50225.0547 - val_mae: 50225.0547
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46656.9961 - mae: 46656.9961 - val_loss: 50222.8711 - val_mae: 50222.8711
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46649.3594 - mae: 46649.3594 - val_loss: 50227.2188 - val_mae: 50227.2188
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46640.9531 - mae: 46640.9531 - val_loss: 50230.7969 - val_mae: 50230.7969
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46637.6719 - mae: 46637.6719 - val_loss: 50231.1719 - val_mae: 50231.1719
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46634.7031 - mae: 46634.7031 - val_loss: 50227.4609 - val_mae: 50227.4609
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 46631.2695 - mae: 46631.2695 - val_loss: 50237.4336 - val_mae: 50237.4336
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46620.6445 - mae: 46620.6445 - val_loss: 50228.6016 - val_mae: 50228.6016
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46614.7266 - mae: 46614.7266 - val_loss: 50226.0156 - val_mae: 50226.0156
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46608.1133 - mae: 46608.1133 - val_loss: 50219.7344 - val_mae: 50219.7344
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46607.2656 - mae: 46607.2656 - val_loss: 50226.8047 - val_mae: 50226.8047
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46597.6836 - mae: 46597.6836 - val_loss: 50242.7344 - val_mae: 50242.7344
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 46597.8945 - mae: 46597.8945 - val_loss: 50241.2539 - val_mae: 50241.2539

In [64]:
## Evaluate the model
%load_ext tensorboard

In [67]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 20772), started 0:03:05 ago. (Use '!kill 20772' to kill it.)

In [69]:
 ## Evaluate model on test data

test_loss,tes_mae = model.evaluate(X_test,y_test)
print(f'Test Mae: {tes_mae}')

7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 50219.7344 - mae: 50219.7344
Test Mae: 50219.734375

In [70]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.